"""hashed_password length set to 255 and not null, is_done default set to True

Revision ID: 0e3ec4539086
Revises: 283f52297fa1
Create Date: 2026-03-10 11:54:58.260641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3ec4539086'
down_revision: Union[str, Sequence[str], None] = '283f52297fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
